@startuml

title tests/publiccloud/run_ltp.pm

' # SUSE's openQA tests
' #
' # Copyright 2018-2021 SUSE LLC
' # SPDX-License-Identifier: FSFAP
' 
' # Package: perl-base ltp
' # Summary: Use perl script to run LTP on public cloud
' #
' # Maintainer: Clemens Famulla-Conrad <cfamullaconrad@suse.de>, qa-c team <qa-c@suse.de>
' 


' ========
' Description:
'  UML metalanguage convertion of the test code in:
'  https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/publiccloud/run_ltp.pm

' Author: Maurizio Dati - mdati@suse.com
' =========

' !pragma useVerticalIf on

' Legend: 
' (def)   = parameter is defined has a value
' (undef) = parameter undefined or empty

'======

start
note
    publiccloud/run_ltp::run()
end note

' sub run {
'     my ($self, $args) = @_;
    : $arch = PUBLIC_CLOUD_ARCH : aarch64 or x86_64 <

    : $ltp_repo = LTP_REPO
       (default https://download.opensuse.org/repositories/benchmark:/ltp:/stable/ + version) <

'     my $provider;
'     my $instance;
' 
    : select_host_console() |
' 
    if (PUBLIC_CLOUD_QAM) then (def)
        : $instance
        $provider; 
    else (undef)
        : $provider = provider_factory() |
        : $instance = $provider->create_instance() |
        if (is_openstack) then (yes)
        else (no)
            :$instance->wait_for_guestregister() |
        endif
    endif
 
    : exec :  
    "cd /root"
    "curl " . data_url("publiccloud/restart_instance.sh") . " -o restart_instance.sh"
    "curl " . data_url("publiccloud/log_instance.sh") . " -o log_instance.sh"
    "chmod +x restart_instance.sh"
    "chmod +x log_instance.sh";

    if (is_byos() && not PUBLIC_CLOUD_QAM) then (yes)
        :registercloudguest($instance) |
    endif

    if (is_openstack) then (yes)
        :register_openstack($instance) |
    endif
    
    : exec : $instance - 
    "sudo zypper -n addrepo -fG " . $ltp_repo . " ltp_repo";
    : $ltp_pkg = LTP_PKG 
        default: "ltp-stable" <
    : exec : $instance - 
    "sudo zypper -n in $ltp_pkg";

    : $ltp_env = gen_ltp_env($instance, $ltp_pkg) |
    
    ' # Use lib/LTP/WhiteList module to exclude tests
    if ('LTP_KNOWN_ISSUES') then (def)
        : $whitelist = LTP::WhiteList]
        : $exclude = LTP_COMMAND_EXCLUDE]
        : @skipped_tests = list_skipped_tests($ltp_env, LTP_COMMAND_FILE) |
        if (@skipped_tests) then (def)
            : $exclude = $exclude + @skipped_tests]
            : LTP_COMMAND_EXCLUDE = $exclude]
        endif
    endif

    :$runltp_ng_repo = "LTP_RUN_NG_REPO" 
        (default "https://github.com/metan-ucw/runltp-ng.git")
    $runltp_ng_branch = "LTP_RUN_NG_BRANCH" 
        (default "master") /

    : exec :
    "git clone -q - -single-branch -b $runltp_ng_branch --depth 1 $runltp_ng_repo";
    : exec : instance
    "sudo CREATE_ENTRIES=1 ' + get_ltproot() + '/IDcheck.sh'"
    "rpm -qa 'kernel*' --qf '%{NAME}\n' | sort | uniq | xargs rpm -qi";

    : $reset_cmd =  
    /root/restart_instance.sh ' + instance_log_args()]
    : $log_start_cmd = 
    /root/log_instance.sh start ' + instance_log_args()]

    : exec : $log_start_cmd;

    : $cmd =
    "perl -I runltp-ng runltp-ng/runltp-ng "
    + "- -logname=ltp_log --verbose "
    + "- -timeout=1200 "
    + "- -run LTP_COMMAND_FILE"
    + "- -exclude LTP_COMMAND_EXCLUDE" 
    + "- -backend=ssh"
    + ":user= $instance->username"
    + ":key_file= $instance->ssh_key"
    + ":host= $instance->public_ip"
    + ":reset_command= $reset_cmd"
    + ":ssh_opts= -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    + "--json_filter=openqa " /

    : exec : $cmd;

stop

'======

start
note
    gen_ltp_rpm()
end note
    : return link from $url >
stop

start
note
    instance_log_args()
end note

    : return 
        PUBLIC_CLOUD_PROVIDER,
        instance_id,
        public_ip,
        region >
stop


start
note
sub upload_ltp_logs()
end note

    ' my ($self) = @_;
    ': my $log_file = '';
    ' if ( $ltp_runtime =~ /^python/i ) then
    '    :$log_file = Mojo::File::path('ulogs/result.json') ]
    '    :upload_logs("$root_dir/result.json", 
    '        log_name => $log_file->basename, 
    '        failok => 1);
    ' else 
        '# default ltp runtime: perl
        :$log_file = Mojo::File::path('ulogs/ltp_log.json') ]
        :upload_logs("$root_dir/ltp_log.raw", 
            log_name => 'ltp_log.raw', 
            failok => 1);
        :upload_logs("$root_dir/ltp_log.json", 
            log_name => $log_file->basename, 
            failok => 1);

    ' endif

    :my $ltp_testsuite = get_required_var('LTP_COMMAND_FILE') ]

    ': upload_logs("$root_dir/result.json", 
    '    log_name => $log_file->basename, 
    '    failok => 1);

    if ( -e $log_file->to_string) then (true)
    else (false)
    : return ;
        stop
    endif

    : <b> local @INC = ($ENV{OPENQA_LIBPATH} // testapi::OPENQA_LIBPATH, @INC) </b> /
    
    ' eval {
        :require OpenQA::Parser::Format::LTP ]

        : read $ltp_log file ;
        : $parser = OpenQA::Parser::Format::LTP ($log_file) ]
        : map test :: results ]
        : $whitelist = LTP::WhiteList  ]

        repeat : for my $result in $parser->results()
            if ($whitelist->override_known_failures(...)) then (true)
                :$result->{result} = 'softfail';
            else (false)
            endif
        repeatwhile ($result)
        
        : $parser->write_output(bmwqemu::result_dir()) |
        : $parser->write_test_result(bmwqemu::result_dir()) |

        :$parser->tests->each(sub {
                $autotest::current_test->register_extra_test_results([$_->to_openqa]);

    ' };
    if ($@) then
        : die $@; 
        end
    endif

stop


start
note
sub cleanup()
end note

    '# Ensure that the ltp script gets killed
    : 'ETX' >
    : $self->upload_ltp_logs() |

    if ( ( {my_instance} && exists file $root_dir/log_instance.sh ) ==0 ) then (true)
        : exec : 
          $root_dir/log_instance.sh stop $self->instance_log_args() 
          cd /tmp/log_instance && tar -zcf $root_dir/instance_log.tar.gz * |
        : upload_logs("$root_dir/instance_log.tar.gz") |
    endif

stop


start
note
    gen_ltp_env()
end note

    : return $environment = 
         product = DISTRI : VERSION
         revision = BUILD
         arch = PUBLIC_CLOUD_ARCH (or "ARCH")
         kernel = exec : 'uname -r'
         backend = BACKEND
         flavor = FLAVOR
         ltp_version = "rpm -q --qf '%{VERSION}\n' $ltp_pkg" >

'     record_info("LTP Environment", Dumper($environment);
stop

@enduml
