@startuml

title main_publiccloud->load_publiccloud_tests:
' ========
' Description:
'  UML metalanguage of test code in:
'  https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/main_publiccloud.pm
'    sub load_publiccloud_tests

' Author: Maurizio Dati - mdati@suse.com
' =========

!pragma useVerticalIf on

start

group load_publiccloud_tests

    if ('PUBLIC_CLOUD_PREPARE_TOOLS') then (1)
        :load_create_publiccloud_tools_image();
        
    (0) elseif ('PUBLIC_CLOUD_TOOLS_CLI') then (1)
        :load_publiccloud_cli_tools();

    else (0)
        : 'boot/boot_to_desktop';
        
group After_boot

        if  ('PUBLIC_CLOUD_MIGRATION') then (1)
            : publiccloud/migration;
        (0) elseif ('PUBLIC_CLOUD_DOWNLOAD_TESTREPO') then (1)
            :load_publiccloud_download_repos();
        (0) elseif ('PUBLIC_CLOUD_QAM') then (1)
            :load_maintenance_publiccloud_tests();
        else (0) 
            :load_latest_publiccloud_tests();
        endif
end group

    endif

end group

stop
