@startuml

title main_publiccloud->load_maintenance_publiccloud_tests:
' ========
' Description:
'  UML metalanguage of test code in:
'  https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/main_publiccloud.pm
'    sub load_maintenance_publiccloud_tests

' Author: Maurizio Dati - mdati@suse.com
' =========

!pragma useVerticalIf on

start

:publiccloud/download_repos,
 publiccloud/prepare_instance;

if (PUBLIC_CLOUD_CONSOLE_TESTS) then(1)
  :publiccloud/check_registercloudguest;
else (0)
  :publiccloud/registration;
endif
:publiccloud/transfer_repos,
 publiccloud/patch_and_reboot;

if (PUBLIC_CLOUD_IMG_PROOF_TESTS) then (1)
  :publiccloud/img_proof;
else (0)
  if('PUBLIC_CLOUD_LTP') then (1)
     :publiccloud/run_ltp;
  else (0)
  
group PC_GROUP
     :publiccloud/ssh_interactive_start;
     :publiccloud/instance_overview
       && not 'PUBLIC_CLOUD_IMG_PROOF_TESTS';

    if ('PUBLIC_CLOUD_CONSOLE_TESTS') then (1)
            :load_publiccloud_consoletests();
    elseif ('PUBLIC_CLOUD_CONTAINERS') then (1)
            :load_container_tests();
  
    elseif ('PUBLIC_CLOUD_XFS') then (1)
            : publiccloud/xfsprepare;
            : xfstests/run;
            : xfstests/generate_report;
    elseif ('PUBLIC_CLOUD_SMOKETEST') then (1)
            : publiccloud/smoketest;
            : publiccloud/sev 
               && ('PUBLIC_CLOUD_CONFIDENTIAL_VM');
            : publiccloud/xen
               && ('PUBLIC_CLOUD_XEN');
            : publiccloud/az_l8s_nvme 
               && ('PUBLIC_CLOUD_INSTANCE_TYPE');
     elseif ('PUBLIC_CLOUD_AZURE_NFS_TEST') then (1)
            : publiccloud/azure_nfs;
     endif

  :publiccloud/ssh_interactive_end;
end group

  endif

endif

stop

@enduml

